<?php

$collectiondata = $block->Receivedata();?>
<div class="block block-content">
    <!-- <form class="form minisearch" id="search_mini_form"action=""> -->
        <div class="field search">
            <div class="control">
                <input class="input-val" maxlength="128" type="text" placeholder="Search for Username">
                <button id="find" class="action primary ">Search</button>
            </div>
        </div>
    <!-- </form> -->
</div>
<div class="add_data"></div>
<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base">Data Collections...!</span>
    </h1>
</div>
<a href="<?php echo $this->getUrl('crud/crud/index'); ?>"><button class="action submit primary" >Register Your Self</button></a>
    <?php $i = 1; ?>
    <div class="dashboard-item-content">

        <table class="admin__table-primary">
            <tr>
                <th class="data-grid-th">S.No.</th>
                <th class="data-grid-th">UserName</th>
                <th class="data-grid-th">FirstName</th>
                <th class="data-grid-th">LastName</th>
                <th class="data-grid-th">Email</th>
                <th class="data-grid-th ed_save">Edit/Save</th>
                <th class="data-grid-th del">Delete</th>  
            </tr>
            
                <?php foreach($collectiondata as $collection):?>
                    <tr class="data-row">
                        <?php $id = $collection['excellence_crud_id'];?>
                        <td  hidden class="edit_id"><?php echo $id;?></td>
                        <td  class="s_no "><?php echo $i;?></td>
                        <td contenteditable="false" class="username"><?php echo $collection['username'];?></td>
                        <td contenteditable="false" class="fname "><?php echo $collection['fristname'];?></td>
                        <td contenteditable="false" class="lastname"><?php echo $collection['lastname'];?></td>
                        <td contenteditable="false" class="email_id "><?php echo $collection['email'];?></td>
                        <td hidden class="pass"><?php echo $collection['password'];?></td>
                        <td class="edittable" title="Edit" ><button class="action primary" >Edit</button></td>
                        <td style="display:none" class="Save" title="Save" ><button class="action primary" >Save</button></td>
                        <td class="Delete"><a href="<?php echo $this->getUrl('crud/form/index/id=.', array('delete_id' => $id));?>"> <button class="action primary"> Delete</button></a></td>
                    </tr>
                    <?php $i++; ?>
                <?php endforeach;?>
            </tr>     
        </table>
    </div>

 <script>
require(
   ['jquery'],
        function($) {
            $('.edittable').click(function () {
                if ($(this).html() == '<button class="action primary">Edit</button>') {
                    var tr_search = $(this).closest("tr");
                    var  currentTD = $(this).closest("tr").find('td');
                    tr_search.find('.Save').show();
                    tr_search.find('.edittable').hide();  
                    $.each(currentTD, function () {
                        currentTD.css("background-color", "lightgrey");
                        $(this).prop('contenteditable', true);
                        $(this).css('padding','4px');
	                    $(this).focus();
                        $(".edittable").prop('contenteditable', false); 
                        $(".s_no").prop('contenteditable', false); 
                        $(".Save").prop('contenteditable', false); 
                        $(".Delete").prop('contenteditable', false);        
                    });
                }
            });
            // to Save Data to database....
            $(".Save").click(function(){
                $(this).prop('contenteditable', false); 
                var row = $(this).closest("tr"); 
                var row_css = $(this).closest("tr").find('td');  
                row_css.css("background-color", "white");  // Find the row
                var table_id = row.find(".edit_id").text();
                var username = row.find(".username").text();
                var fname = row.find(".fname").text();
                var lname = row.find(".lastname").text();
                var e_mail_ad = row.find(".email_id").text();
                var p_wd = row.find(".pass").text();  
                $.ajax({
                    url:"<?php echo $this->getUrl('crud/form/index');?>",
                    data:{id:table_id,uname:username,fname:fname,lname:lname,email_ad:e_mail_ad,pwd:p_wd},
                    type:'POST',
                    success:function(response){
                        if(response){
                            window.location.reload();
                        }
                    }
                });
            }); 
            $("#find").click(function(){
                var search_user_val = $(".input-val").val();
                $.ajax({
                    url:"<?php echo $this->getUrl('crud/display/index');?>",
                    data:{u_name:search_user_val},
                    type:'POST',
                    success:function(response){

                        var rr = JSON.parse(response);
                
                         $(".ed_save").hide();
                         $(".del").hide();
                         $(".data-row").html("");
                        for(var i=0;i<rr.count;i++)
                        {
                            $(".admin__table-primary").append('<tr class="data-row"><td>'+(i+1)+'</td><td  class="username">'+rr[i].username+'</td><td  class="firstname">'+rr[i].f_name+'</td><td  class="lastname">'+rr[i].l_name+'</td><td  class="email">'+rr[i].e_mail+'</td><td hidden  class="pass">'+rr[i].pass+'</td></tr>');
                        }
                      
                    }
                });
            });        
        }
    );
</script>
